#version: "3.9"

services:
  web:
    build: .
    container_name: hopital-web
    restart: unless-stopped
    
    ports:
      - "5002:5002"
    
    environment:
      FLASK_ENV: production
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: Azerty1234
      DB_NAME: hopital_db
      SECRET_KEY: ${SECRET_KEY:-votre-cle-secrete-changez-moi}
    
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
    
    depends_on:
      - mysql
    
    networks:
      - hopital-network

  mysql:
    image: mysql:8.0
    container_name: hopital-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Azerty1234
      MYSQL_DATABASE: hopital_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Azerty1234

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
    
    networks:
      - hopital-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hopital-phpmyadmin

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8080:80"
    
    networks:
      - hopital-network

networks:
  hopital-network:
    driver: bridge

volumes:
  mysql_data:
